name: Feature request
description: Suggest an idea for this project
labels: [ enhancement ]

body:
  - type: markdown
    attributes:
      value: |
        Provide a summary of the feature request in the title above.

  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if an issue already exists for the feature that you want to add.
      options:
      - label: I have searched the existing issues
        required: true

  - type: textarea
    id: description
    attributes:
      label: Describe what you would like added or changed
      description: |
        - Write if the feature you asked for solves a problem that bores you
        - Write what you would like implemented
    validations:
      required: true
