name: Railcraft CI

on:
  push:
    branches:
    - 1.20.x
  pull_request:
    branches:
    - 1.20.x
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Compile
        run: ./gradlew build --max-workers 1

      - name: Test
        run: ./gradlew runGameTestServer --max-workers 1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Railcraft-1.20.x-GitHub
          path: build/libs
