name: Railcraft CI

on:
  push:
    branches:
    - 1.20.x
  pull_request:
    branches:
    - 1.20.x
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Validate wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew runGameTestServer

      - name: Upload Artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: Railcraft-1.20.x-GitHub
          path: build/libs

  publish:
    if: github.event_name == 'pull_request'
    name: Pull request artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/github-script@v7
        env:
          URL: ${{needs.build.outputs.output1}}
        with:
          script: |
            const { URL } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '[Click here](' + URL + ') to download the latest build'
            })
