name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Compile
        run: ./gradlew build --no-daemon --max-workers 1

      - name: Test
        run: ./gradlew runGameTestServer --no-daemon --max-workers 1

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Make Changelog
        run: ./gradlew makeChangelog --no-daemon --max-workers 1

      - name: Publish
        run: ./gradlew publishModrinth --no-daemon --max-workers 1
